-- ============================================================
-- MIGRATION — blog_posts
-- Stores journal articles generated by marketing agents.
-- ============================================================

CREATE TABLE blog_posts (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug          TEXT        UNIQUE NOT NULL,
  title         TEXT        NOT NULL,
  excerpt       TEXT        NOT NULL,
  body          TEXT        NOT NULL DEFAULT '',
  category      TEXT        NOT NULL,
  read_time     TEXT        NOT NULL DEFAULT '5 min read',
  author        TEXT        NOT NULL DEFAULT 'Pristine Detailers',
  agent_name    TEXT,                          -- which agent wrote it
  status        TEXT        NOT NULL DEFAULT 'draft'
                            CHECK (status IN ('draft', 'published', 'archived')),
  published_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_blog_posts_status       ON blog_posts(status);
CREATE INDEX idx_blog_posts_published_at ON blog_posts(published_at DESC);
CREATE INDEX idx_blog_posts_category     ON blog_posts(category);

-- Auto-set published_at when status flips to published
CREATE OR REPLACE FUNCTION set_published_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'published' AND OLD.status != 'published' THEN
    NEW.published_at = NOW();
  END IF;
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER blog_posts_published_at
  BEFORE UPDATE ON blog_posts
  FOR EACH ROW EXECUTE FUNCTION set_published_at();

-- RLS: public can read published posts; service role can do everything
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published posts are publicly readable"
  ON blog_posts FOR SELECT
  USING (status = 'published');

CREATE POLICY "Service role has full access"
  ON blog_posts FOR ALL
  USING (auth.role() = 'service_role');

-- Seed with the existing hardcoded articles (published)
INSERT INTO blog_posts (slug, title, excerpt, category, read_time, status, published_at, created_at) VALUES
(
  'ceramic-coating-vs-wax',
  'Ceramic Coating vs. Wax: Why the Upgrade Makes Sense',
  'Wax protects for weeks. Ceramic protects for years. We break down the chemistry, cost, and real-world difference between the two — and when each is the right call.',
  'Ceramic Coating',
  '5 min read',
  'published',
  '2026-04-01',
  '2026-04-01'
),
(
  'ppf-guide-melbourne',
  'The Complete Melbourne Guide to Paint Protection Film',
  'Stone chips on the freeway. Gravel roads on the Mornington Peninsula. Bird droppings in Toorak. PPF is designed for real-world conditions — here is everything you need to know before committing.',
  'Paint Protection Film',
  '8 min read',
  'published',
  '2026-03-01',
  '2026-03-01'
),
(
  'membership-savings-calculator',
  'How Much Does a Pristine Membership Actually Save You?',
  'We ran the numbers on a typical member across 12 months — washes, discount on ceramic, priority bookings. The result might surprise you.',
  'Membership',
  '4 min read',
  'published',
  '2026-03-15',
  '2026-03-15'
),
(
  'paint-correction-explained',
  'Paint Correction Explained: Swirls, Scratches, and the Machine Behind the Magic',
  'Most paint defects are in the clear coat — not the paint itself. That means they can be removed entirely without respray. Here is how our technicians approach a correction job.',
  'Detailing',
  '6 min read',
  'published',
  '2026-02-01',
  '2026-02-01'
),
(
  'ceramic-coating-maintenance',
  'How to Maintain a Ceramic Coating (and Keep Your Warranty Valid)',
  'A ceramic coating is a long-term investment. The way you wash, park, and care for it over the next 3–8 years determines whether you keep that mirror finish — or lose it to contamination.',
  'Ceramic Coating',
  '5 min read',
  'published',
  '2026-01-15',
  '2026-01-15'
),
(
  'mobile-detailing-vs-fixed',
  'Mobile Detailing vs. Fixed Workshop: Which Is Better for Your Car?',
  'We might be biased — but the case for mobile is stronger than you think. Controlled environment, no waiting room, and the same products and certifications as any fixed studio.',
  'Detailing',
  '4 min read',
  'published',
  '2025-12-01',
  '2025-12-01'
);
